create table public.decline_posts (
  id bigint generated by default as identity not null,
  public_id uuid not null default gen_random_uuid (),
  decline_situation character varying not null,
  actual_situation json null,
  actual_feeling json null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  user_id bigint not null,
  demerit json null,
  constraint decline_posts_pkey primary key (id),
  constraint decline_posts_public_id_key unique (public_id),
  constraint decline_posts_user_id_fkey foreign KEY (user_id) references users (id) on update CASCADE on delete set null
) TABLESPACE pg_default;

create function insert_decline_post_templates(_user_id integer, _decline_sitiation text, _actual_situation json, _actual_feeling json, _demerit json, _templates_json json) RETURNS uuid
 AS $$ 
DECLARE
  new_post_public_id uuid;
  new_post_id integer;
  rec RECORD;
BEGIN
  INSERT INTO decline_posts(user_id,decline_situation, actual_situation, actual_feeling, demerit) 
    VALUES (_user_id, _decline_sitiation, _actual_situation,_actual_feeling,_demerit)
    RETURNING id, public_id INTO new_post_id, new_post_public_id;

  FOR rec IN
    SELECT
      *
    FROM
      json_to_recordset(_templates_json)
      AS rec
      (
        opening_text text,
        closing_text text,
        done_flag boolean,
        done_result text
      )
  LOOP
    INSERT INTO decline_templates(post_id, opening_text, closing_text, done_flag, done_result)
      VALUES (new_post_id, rec.opening_text, rec.closing_text, rec.done_flag, rec.done_result);
  END LOOP;

  return new_post_public_id;
END
$$ LANGUAGE plpgsql

