create table public.decline_templates (
  id bigint generated by default as identity not null,
  post_id bigint not null,
  opening_text character varying null,
  closing_text character varying null,
  done_flag boolean not null,
  done_result character varying null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint decline_templates_pkey primary key (id),
  constraint decline_templates_post_id_fkey foreign KEY (post_id) references decline_posts (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;