create table public.users (
  id bigint generated by default as identity not null,
  user_name character varying not null,
  email character varying not null,
  created_at timestamp with time zone not null default now(),
  auth_id uuid null,
  constraint users_pkey primary key (id),
  constraint users_user_name_key unique (user_name),
  constraint users_auth_id_fkey foreign KEY (auth_id) references auth.users (id) on update CASCADE on delete CASCADE
) TABLESPACE pg_default;

CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
INSERT INTO public.users (auth_id, user_name, email)
 VALUES (NEW.id, NEW.raw_user_meta_data->>'user_name', NEW.email);
 RETURN NEW;
END;
$$;

create trigger on_auth_user_created
after insert on auth.users for each row
execute function handle_new_user();