
  create table "public"."decline_posts" (
    "id" bigint generated by default as identity not null,
    "public_id" uuid not null default gen_random_uuid(),
    "decline_situation" character varying not null,
    "actual_situation" json,
    "actual_feeling" json,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now(),
    "user_id" bigint not null,
    "demerit" json
      );



  create table "public"."decline_templates" (
    "id" bigint generated by default as identity not null,
    "post_id" bigint not null,
    "opening_text" character varying,
    "closing_text" character varying,
    "done_flag" boolean not null,
    "done_result" character varying,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone not null default now()
      );



  create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "user_name" character varying not null,
    "email" character varying not null,
    "created_at" timestamp with time zone not null default now(),
    "auth_id" uuid
      );


CREATE UNIQUE INDEX decline_posts_pkey ON public.decline_posts USING btree (id);

CREATE UNIQUE INDEX decline_posts_public_id_key ON public.decline_posts USING btree (public_id);

CREATE UNIQUE INDEX decline_templates_pkey ON public.decline_templates USING btree (id);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX users_user_name_key ON public.users USING btree (user_name);

alter table "public"."decline_posts" add constraint "decline_posts_pkey" PRIMARY KEY using index "decline_posts_pkey";

alter table "public"."decline_templates" add constraint "decline_templates_pkey" PRIMARY KEY using index "decline_templates_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."decline_posts" add constraint "decline_posts_public_id_key" UNIQUE using index "decline_posts_public_id_key";

alter table "public"."decline_posts" add constraint "decline_posts_user_id_fkey" FOREIGN KEY (user_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE SET NULL not valid;

alter table "public"."decline_posts" validate constraint "decline_posts_user_id_fkey";

alter table "public"."decline_templates" add constraint "decline_templates_post_id_fkey" FOREIGN KEY (post_id) REFERENCES public.decline_posts(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."decline_templates" validate constraint "decline_templates_post_id_fkey";

alter table "public"."users" add constraint "users_auth_id_fkey" FOREIGN KEY (auth_id) REFERENCES auth.users(id) ON UPDATE CASCADE ON DELETE CASCADE not valid;

alter table "public"."users" validate constraint "users_auth_id_fkey";

alter table "public"."users" add constraint "users_user_name_key" UNIQUE using index "users_user_name_key";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
BEGIN
INSERT INTO public.users (auth_id, user_name, email)
 VALUES (NEW.id, NEW.raw_user_meta_data->>'user_name', NEW.email);
 RETURN NEW;
END;
$function$
;

CREATE OR REPLACE FUNCTION public.insert_decline_post_templates(_user_id integer, _decline_sitiation text, _actual_situation json, _actual_feeling json, _demerit json, _templates_json json)
 RETURNS uuid
 LANGUAGE plpgsql
AS $function$ 
DECLARE
  new_post_public_id uuid;
  new_post_id integer;
  rec RECORD;
BEGIN
  INSERT INTO decline_posts(user_id,decline_situation, actual_situation, actual_feeling, demerit) 
    VALUES (_user_id, _decline_sitiation, _actual_situation,_actual_feeling,_demerit)
    RETURNING id, public_id INTO new_post_id, new_post_public_id;

  FOR rec IN
    SELECT
      *
    FROM
      json_to_recordset(_templates_json)
      AS rec
      (
        opening_text text,
        closing_text text,
        done_flag boolean,
        done_result text
      )
  LOOP
    INSERT INTO decline_templates(post_id, opening_text, closing_text, done_flag, done_result)
      VALUES (new_post_id, rec.opening_text, rec.closing_text, rec.done_flag, rec.done_result);
  END LOOP;

  return new_post_public_id;
END
$function$
;

grant delete on table "public"."decline_posts" to "anon";

grant insert on table "public"."decline_posts" to "anon";

grant references on table "public"."decline_posts" to "anon";

grant select on table "public"."decline_posts" to "anon";

grant trigger on table "public"."decline_posts" to "anon";

grant truncate on table "public"."decline_posts" to "anon";

grant update on table "public"."decline_posts" to "anon";

grant delete on table "public"."decline_posts" to "authenticated";

grant insert on table "public"."decline_posts" to "authenticated";

grant references on table "public"."decline_posts" to "authenticated";

grant select on table "public"."decline_posts" to "authenticated";

grant trigger on table "public"."decline_posts" to "authenticated";

grant truncate on table "public"."decline_posts" to "authenticated";

grant update on table "public"."decline_posts" to "authenticated";

grant delete on table "public"."decline_posts" to "service_role";

grant insert on table "public"."decline_posts" to "service_role";

grant references on table "public"."decline_posts" to "service_role";

grant select on table "public"."decline_posts" to "service_role";

grant trigger on table "public"."decline_posts" to "service_role";

grant truncate on table "public"."decline_posts" to "service_role";

grant update on table "public"."decline_posts" to "service_role";

grant delete on table "public"."decline_templates" to "anon";

grant insert on table "public"."decline_templates" to "anon";

grant references on table "public"."decline_templates" to "anon";

grant select on table "public"."decline_templates" to "anon";

grant trigger on table "public"."decline_templates" to "anon";

grant truncate on table "public"."decline_templates" to "anon";

grant update on table "public"."decline_templates" to "anon";

grant delete on table "public"."decline_templates" to "authenticated";

grant insert on table "public"."decline_templates" to "authenticated";

grant references on table "public"."decline_templates" to "authenticated";

grant select on table "public"."decline_templates" to "authenticated";

grant trigger on table "public"."decline_templates" to "authenticated";

grant truncate on table "public"."decline_templates" to "authenticated";

grant update on table "public"."decline_templates" to "authenticated";

grant delete on table "public"."decline_templates" to "service_role";

grant insert on table "public"."decline_templates" to "service_role";

grant references on table "public"."decline_templates" to "service_role";

grant select on table "public"."decline_templates" to "service_role";

grant trigger on table "public"."decline_templates" to "service_role";

grant truncate on table "public"."decline_templates" to "service_role";

grant update on table "public"."decline_templates" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";

CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


